apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^categories/', include('category.urls', namespace='category')),
    url(r'^$', 'apps.views.home'),
]

category/urls.py
from django.conf.urls import patterns, url

from category import views

urlpatterns = patterns('',
  url(r'^$', views.CategoryList.as_view(), name='category_list'),
  url(r'^new$', views.CategoryCreate.as_view(), name='category_new'),
  url(r'^edit/(?P<pk>\d+)$', views.CategoryUpdate.as_view(), name='category_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.CategoryDelete.as_view(), name='category_delete'),
)

category/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category:category_edit', kwargs={'pk': self.pk})

apps/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse


def home(request):
    html = """
    <h1>Django CRUD Example</h1>
    <a href="/category/">Class Based Views</a><br> 
    """
    return HttpResponse(html)

category/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from category.models import Category


class CategoryList(ListView):
    model = Category


class CategoryCreate(CreateView):
    model = Category
    fields = ['name']
    success_url = reverse_lazy('category:category_list')


class CategoryUpdate(UpdateView):
    model = Category
    fields = ['name']
    success_url = reverse_lazy('category:category_list')


class CategoryDelete(DeleteView):
    model = Category
    success_url = reverse_lazy('category:category_list')

category/templates/category/category_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

category/templates/category/category_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

category/templates/category/category_list.html
<h1>Categories CBV</h1>
<ul>
    {% for category in object_list %}
    <li>{{ category.name }}
    <a href="{% url 'category:category_edit' category.id %}">edit</a>
    <a href="{% url 'category:category_delete' category.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'category:category_new' %}">New</a>